# Generated by Django 2.2.6 on 2019-10-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mn', models.CharField(max_length=25)),
                ('collect_time', models.CharField(max_length=50)),
                ('create_time', models.CharField(max_length=50)),
                ('do', models.CharField(max_length=20)),
                ('temp', models.CharField(max_length=20)),
                ('cod', models.CharField(max_length=20)),
                ('cond', models.CharField(max_length=20)),
                ('ph', models.CharField(max_length=20)),
                ('nh3', models.CharField(max_length=20)),
                ('tp', models.CharField(max_length=20)),
                ('orp', models.CharField(max_length=20)),
                ('zd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mn', models.CharField(max_length=25)),
                ('detial', models.CharField(max_length=100)),
            ],
        ),
    ]
